volumes:
  postgres_data_log_parser:

services:
  backend_log_parser:
    build:
      context: ./src
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - postgres_log_parser
      - redis_log_parser
    volumes:
      - ./src:/app
    command: >
      sh -c "pip install -r requirements.txt && python3 manage.py migrate && python3 manage.py collectstatic && gunicorn --log-file=- --timeout 60 --bind 0.0.0.0:8000 project.wsgi:application --workers=3 --threads=2 --worker-class=gthread
      "
    restart: always
    env_file: ./src/.env
    ports:
      - 8001:8000

  postgres_log_parser:
    image: postgres:13.6
    volumes:
      - postgres_data_log_parser:/var/lib/postgresql/data
    env_file: ./src/.env
    ports:
      - 37223:5432

  redis_log_parser:
    image: "redis:latest"
    ports:
      - "6389:6379"