# Generated by Django 5.1 on 2024-08-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NginxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('method', models.CharField()),
                ('request_URI', models.CharField()),
                ('response_code', models.IntegerField()),
                ('response_size', models.IntegerField()),
            ],
        ),
    ]
